### ISSUE TITLE
Comprobar la eficiencia estándares en los procesos de desarrollo.

### ISSUE THREAD

**Issue by joseda77** [calidadudea/CalidadForever#14]
Se debe verificar las eficiencia de los estándares aplicados para realizar el proceso de desarrollo.

**Comment by andresr98** [comment]
Se hacen revisiones semanalas del equipo desarrollador junto con diseño. Para cada Release se toman acciones en caso de ser necesario. El archivo adjunto presenta un resumen de las actividades del desarrollo de la plataforma SIMOCU
[Resumen -- Diseño.pdf](https://github.com/calidadudea/CalidadForever/files/3682025/Resumen.--.Diseno.pdf)
