### ISSUE TITLE
Definir métricas para evaluar los cronogramas de entrega.

### ISSUE THREAD

**Issue by joseda77** [calidadudea/CalidadForever#16]
Cada integrante deberá investigar y redactar un documento sobre las métricas de evaluación de calidad para su celular asignada y adjuntarla en este issue

**Comment by luis8alopez** [comment]
[Métricas Gestión.pdf](https://github.com/calidadudea/CalidadForever/files/3679669/Metricas.Gestion.pdf)

**Comment by EvelasquezV** [comment]
Adjunto metricas para evaluar la calidad de la celula de testing
[Metricas Testing.pdf](https://github.com/calidadudea/CalidadForever/files/3689171/Metricas.Testing.pdf)

**Comment by cristian030399** [comment]
[Metricas desarrollo.pdf](https://github.com/calidadudea/CalidadForever/files/3689239/Metricas.desarrollo.pdf)
