### ISSUE TITLE
Conocer los requisitos del sistema.

### ISSUE THREAD

**Issue by joseda77** [calidadudea/CalidadForever#21]
Es de suma importancia para el desarrollo de SIMOCU que se tengan en claro los requisitos funcionales del sistema, de modo que los demás equipos puedan conocer cuál es el objetivo de desarrollar la plataforma.

- [x] Asignar un subgrupo para realizar la definición de requisitos.
- [x] Corregir errores. (En Caso de ser necesario).

**Comment by andresr98** [comment]
Se revisa documento creado por Diseño Y Arquitectura y se encuentran bien definidos los requisitos de la plataforma.
