### ISSUE TITLE
Definir el cronograma de la revisión de calidad en los grupos.

### ISSUE THREAD

**Issue by joseda77** [calidadudea/CalidadForever#23]
Se debe realizar un story mapping, revisando cada fecha existente y ajustando estas por cada Release.

Se debe considerar los siguientes items.
- [x] Documentar y graficar cronogramas.
- [x] Ajustar fechas en caso de inconvenientes.

**Comment by andresr98** [comment]
Se hizo una revisión a cada repositorio de los subgrupos de SIMOCU y se definen los tiempos de entrega en los Milestones.
