### ISSUE TITLE
Determinar normas y estándares de calidad para la construcción de software

### ISSUE THREAD

**Issue by joseda77** [calidadudea/CalidadForever#25]
Se debe realizar una selección exhaustiva de los estándares utilizados para los procesos de desarrollo y construcción del proyecto. 

Se debe considerar los siguientes items.
- [x] Documentar y referenciar estándar.
- [x] Adaptar las normas o estándares elegidos para el proyecto.
- [x] Evaluar cada estándar.
- [x] Realizar selección de los estándares para el proyecto.

**Comment by andresr98** [comment]
Se revisa diagrama generado por el grupo de diseño bajo métricas establecidas en el documento adjunto.
[Métricas de Diseño.pdf](https://github.com/calidadudea/CalidadForever/files/3681989/Metricas.de.Diseno.pdf)
