### ISSUE TITLE
Verificar los estándares de calidad para la selección de la metodología de desarrollo

### ISSUE THREAD

**Issue by joseda77** [calidadudea/CalidadForever#28]
De acuerdo con los estándares encontrados, definir los apropiados al proyecto. Se debe cumplir con lo siguiente:
- [x] Documentar y referenciar estándar.
- [x] Adaptar a la metodología elegida para el proyecto.
- [x] Evaluar cada estándar.
- [x] Realizar selección de los estándares para el proyecto.

**Comment by DiegOliveros** [comment]
@calidadudea/calidad muy buenos días, dónde están las historias cerradas. en este repo sólo hay una y es una versión de prueba. Quedo atento.
