### ISSUE TITLE
Asignar un equipo de pruebas que verifique la calidad de las pruebas

### ISSUE THREAD

**Issue by joseda77** [calidadudea/CalidadForever#8]
Es importante para el desarrollo del proyecto SIMOCU que sea asignado un equipo para la función de Testing de la plataforma.

- [x] Asignar un equipo de Testing en el curso.
- [x] Reportar novedades en la asignación del equipo.
- [x] Subir el informe resultante.

**Comment by andresr98** [comment]
Equipo de Testing asignado correctamente por Diego Oliveros (Product Owner), y puede ser consultado en la carpeta de Drive del curso
